#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calc.Resource", IsApplication=true)]

namespace Calc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ppp = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int Button0 = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int Button1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Button2 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Button3 = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int Button4 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Button5 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Button6 = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Button7 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Button8 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Button9 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int ButtonCE = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int Buttonadd = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int Buttonadddiff = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int Buttonbackspace = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int Buttondiff = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int Buttondiv = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int Buttonequal = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int Buttonmul = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int Buttonpoint = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int Buttonreset = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Edittext = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int Textview3 = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int backspace = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
